
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU AGPL 3.0"
[[mods]] #mandatory
modId="enhancedarmaments" #mandatory
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="EnhancedArmaments" #mandatory
logoFile="icon.png" #optional
authors="cnlimiter" #optional
description='''

'''
[[dependencies.enhancedarmaments]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"

